stages:
    - build

variables:
    PREBUILT_SDK_ENV: "/home/kist_ci/yocto_sdk/install/environment-setup-armv7ahf-vfpv4d16-openbmc-linux-gnueabi"

build_itm:
    image: kist_ci_docker
    stage: build
    script:
        - . $PREBUILT_SDK_ENV
        - meson setup out
        - meson compile -C out ist kist_itm
    artifacts:
        untracked: true
